version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db        # This is the hostname that should match the service name
      - DB_USER=root
      - DB_PASSWORD=bobby
      - DB_NAME=contact_us
    depends_on:
      - db                 # Ensures that MySQL starts first

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bobby
      MYSQL_DATABASE: contact_us
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
